// Starting catalogue from the 4 Sep 2026 inventory. Buying costs are deliberately not included.
export const SEED = [
{
"sku": "EOS-LOT-CW-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Coconut Waters",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 1,
"cat": "Body care",
"shape": "pump",
"c": [
"#7FD1D0",
"#F4FAF9",
"#FFFFFF",
"#2E9C9A",
"#DDF2F0"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-WASH-CW-473",
"brand": "EOS",
"product": "Cashmere Body Wash",
"variant": "Coconut Waters",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 3,
"cat": "Shower",
"shape": "flip",
"c": [
"#7FD1D0",
"#F4FAF9",
"#FFFFFF",
"#2E9C9A",
"#DDF2F0"
],
"notes": "",
"cond": "New",
"price": 3000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-LOT-PR-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Pomegranate Raspberry",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 1,
"cat": "Body care",
"shape": "pump",
"c": [
"#C7285C",
"#F6E3EA",
"#FFF4F7",
"#8E1640",
"#F7DCE5"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-LOT-PC-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Pink Champagne",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 4,
"cat": "Body care",
"shape": "pump",
"c": [
"#F2B8C6",
"#FFF1F4",
"#FFFFFF",
"#C9637E",
"#FBE7EC"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-WASH-PC-473",
"brand": "EOS",
"product": "Cashmere Body Wash",
"variant": "Pink Champagne",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 5,
"cat": "Shower",
"shape": "flip",
"c": [
"#F2B8C6",
"#FFF1F4",
"#FFFFFF",
"#C9637E",
"#FBE7EC"
],
"notes": "",
"cond": "New",
"price": 3000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-LOT-VC-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Vanilla Cashmere",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 6,
"cat": "Body care",
"shape": "pump",
"c": [
"#E9D3B4",
"#FBF4E9",
"#FFFDF8",
"#A9804C",
"#F5EBDD"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-LOT-FC-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Fresh + Cozy",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 3,
"cat": "Body care",
"shape": "pump",
"c": [
"#B9C3EA",
"#F1F3FC",
"#FFFFFF",
"#5D6BB3",
"#E5E9F8"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-WASH-FC-473",
"brand": "EOS",
"product": "Cashmere Body Wash",
"variant": "Fresh & Cozy",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 4,
"cat": "Shower",
"shape": "flip",
"c": [
"#B9C3EA",
"#F1F3FC",
"#FFFFFF",
"#5D6BB3",
"#E5E9F8"
],
"notes": "",
"cond": "New",
"price": 3000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-LOT-JP-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Jasmine Peach",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 2,
"cat": "Body care",
"shape": "pump",
"c": [
"#F6B98E",
"#FFF1E6",
"#FFFFFF",
"#D07A3D",
"#FCE8D9"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-LOT-SD-473",
"brand": "EOS",
"product": "24H Moisture Body Lotion",
"variant": "Strawberry Dream",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 2,
"cat": "Body care",
"shape": "pump",
"c": [
"#EE6F7B",
"#FFE9EB",
"#FFFFFF",
"#B8323F",
"#FCE0E2"
],
"notes": "",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-WASH-VC-473",
"brand": "EOS",
"product": "Cashmere Body Wash",
"variant": "Vanilla Cashmere",
"size": "16 fl oz / 473 mL",
"ml": "473 mL",
"qty": 5,
"cat": "Shower",
"shape": "flip",
"c": [
"#E9D3B4",
"#FBF4E9",
"#FFFDF8",
"#A9804C",
"#F5EBDD"
],
"notes": "",
"cond": "New",
"price": 3000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-GP-DUO-1L",
"brand": "Luseta",
"product": "Glossy Pearl Shampoo & Conditioner Duo Pack",
"variant": "Glossy Pearl",
"size": "2 × 33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Hair",
"shape": "duo",
"c": [
"#EDE7F1",
"#C9B8D6",
"#FFFFFF",
"#8D72A6",
"#EFE9F4"
],
"notes": "Contains one shampoo and one conditioner; for all hair types",
"cond": "New",
"price": 5600,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-KER-DUO-1L",
"brand": "Luseta",
"product": "Keratin Shampoo & Conditioner Duo Pack",
"variant": "Keratin",
"size": "2 × 33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Hair",
"shape": "duo",
"c": [
"#D8B26E",
"#2B2320",
"#FFF8EA",
"#8A6420",
"#F3E7CF"
],
"notes": "Contains one shampoo and one conditioner; for damaged and dry hair",
"cond": "New",
"price": 5600,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "BYP-SG-ARG-1L",
"brand": "Byphasse",
"product": "Dermo Micellar Shower Gel",
"variant": "Argan",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 3,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#E8A33B",
"#5B3A1A",
"#FFF6E4",
"#9C5E12",
"#F7E4C3"
],
"notes": "Argan oil; pH neutral; suitable for all skin types",
"cond": "New",
"price": 5200,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DIF-RM-DUO-1L",
"brand": "Difeel",
"product": "Rosemary & Mint Shampoo & Conditioner Duo",
"variant": "Rosemary & Mint with Biotin",
"size": "2 × 33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Hair",
"shape": "duo",
"c": [
"#6FAE86",
"#1F4D35",
"#F4FBF6",
"#2E7250",
"#DCEFE2"
],
"notes": "Unboxed duo; contains one shampoo and one conditioner",
"cond": "New",
"price": null,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DIF-BAT-DUO-1L",
"brand": "Difeel",
"product": "Batana Shampoo & Conditioner Duo",
"variant": "Batana",
"size": "2 × 33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Hair",
"shape": "duo",
"c": [
"#8A5A3C",
"#E9D8C7",
"#FFF8F1",
"#5C3620",
"#EEDDCF"
],
"notes": "Unboxed sulfate-free duo; contains one shampoo and one conditioner",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-CC-BW-1L",
"brand": "Luseta",
"product": "Citrus & Collagen Body Wash",
"variant": "Citrus & Collagen",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#F7C948",
"#F18A2A",
"#FFFDF2",
"#C36A12",
"#FCF0C8"
],
"notes": "Energizing and hydrating; free of sulfates, parabens and gluten; for all skin types",
"cond": "New",
"price": 5400,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-SA-BW-1L",
"brand": "Luseta",
"product": "Shea Butter & Argan Oil Body Wash",
"variant": "Shea Butter & Argan Oil",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 4,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#E6CFA3",
"#8A6A3A",
"#FFFBF2",
"#8A6A3A",
"#F4EAD6"
],
"notes": "Hydrating and moisturizing; free of sulfates, parabens and gluten; for all skin types",
"cond": "New",
"price": 3500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-BUT-VC-283",
"brand": "EOS",
"product": "Cashmere Whipped Oil Butter",
"variant": "Vanilla Cashmere",
"size": "10 oz / 283 g",
"ml": "283 g",
"qty": 3,
"cat": "Body care",
"shape": "jar",
"c": [
"#E9D3B4",
"#FBF4E9",
"#FFFDF8",
"#A9804C",
"#F5EBDD"
],
"notes": "Shea Better body butter",
"cond": "New",
"price": 5000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "FEN-DC-RICH-340",
"brand": "Fenty Hair",
"product": "Moisture Repair Deep Conditioner",
"variant": "The Richer One",
"size": "11.5 fl oz / 340 mL",
"ml": "340 mL",
"qty": 4,
"cat": "Hair",
"shape": "tube",
"c": [
"#F1E6D8",
"#3B2F2A",
"#FFFFFF",
"#8C6B55",
"#EFE4D8"
],
"notes": "Deep conditioning moisture repair treatment",
"cond": "New",
"price": 11600,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "EOS-OIL-VC-177",
"brand": "EOS",
"product": "Cashmere Body Oil",
"variant": "Vanilla Cashmere",
"size": "6 fl oz / 177 mL",
"ml": "177 mL",
"qty": 3,
"cat": "Body care",
"shape": "oil",
"c": [
"#E9D3B4",
"#FBF4E9",
"#FFFDF8",
"#A9804C",
"#F5EBDD"
],
"notes": "24-hour moisture; plant-based squalane",
"cond": "New",
"price": 5000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-DS-CE-107",
"brand": "Dove",
"product": "Advanced Care Dry Spray Antiperspirant Deodorant",
"variant": "Cool Essentials",
"size": "3.8 oz / 107 g",
"ml": "107 g",
"qty": 4,
"cat": "Deodorant",
"shape": "aerosol",
"c": [
"#9FD6E8",
"#EAF6FA",
"#FFFFFF",
"#2B7FA1",
"#DDF0F6"
],
"notes": "72-hour protection; pro-ceramide technology",
"cond": "New",
"price": 2300,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-ST-BF-74",
"brand": "Dove",
"product": "Advanced Care Antiperspirant Deodorant Stick",
"variant": "Beauty Finish",
"size": "2.6 oz / 74 g",
"ml": "74 g",
"qty": 1,
"cat": "Deodorant",
"shape": "stick",
"c": [
"#F4C6D4",
"#FDF1F5",
"#FFFFFF",
"#C25A7D",
"#FBE6ED"
],
"notes": "72-hour protection; pro-ceramide technology",
"cond": "New",
"price": 2000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-ST-CC-74",
"brand": "Dove",
"product": "Advanced Care Antiperspirant Deodorant Stick",
"variant": "Caring Coconut",
"size": "2.6 oz / 74 g",
"ml": "74 g",
"qty": 1,
"cat": "Deodorant",
"shape": "stick",
"c": [
"#F3EEE4",
"#DCC9A8",
"#FFFFFF",
"#9B7A44",
"#F2EADC"
],
"notes": "72-hour protection; pro-ceramide technology",
"cond": "New",
"price": 2000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-ST-CE-74",
"brand": "Dove",
"product": "Advanced Care Antiperspirant Deodorant Stick",
"variant": "Cool Essentials",
"size": "2.6 oz / 74 g",
"ml": "74 g",
"qty": 2,
"cat": "Deodorant",
"shape": "stick",
"c": [
"#9FD6E8",
"#EAF6FA",
"#FFFFFF",
"#2B7FA1",
"#DDF0F6"
],
"notes": "72-hour protection; pro-ceramide technology",
"cond": "New",
"price": 2000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-ST-RP-74",
"brand": "Dove",
"product": "Advanced Care Antiperspirant Deodorant Stick",
"variant": "Rose Petals",
"size": "2.6 oz / 74 g",
"ml": "74 g",
"qty": 1,
"cat": "Deodorant",
"shape": "stick",
"c": [
"#E9A3B6",
"#FCEFF3",
"#FFFFFF",
"#B2466A",
"#F9E1E8"
],
"notes": "72-hour protection; pro-ceramide technology",
"cond": "New",
"price": 2000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-ST-OC-74",
"brand": "Dove",
"product": "Antiperspirant Deodorant Stick",
"variant": "Original Clean",
"size": "2.6 oz / 74 g",
"ml": "74 g",
"qty": 1,
"cat": "Deodorant",
"shape": "stick",
"c": [
"#FFFFFF",
"#D7E3EE",
"#FFFFFF",
"#2F5E8C",
"#E4ECF3"
],
"notes": "48-hour sweat and odor protection; moisturizers",
"cond": "New",
"price": 2000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-ST-SC-74",
"brand": "Dove",
"product": "Advanced Care Antiperspirant Deodorant Stick",
"variant": "Sheer Cool",
"size": "2.6 oz / 74 g",
"ml": "74 g",
"qty": 1,
"cat": "Deodorant",
"shape": "stick",
"c": [
"#BFE3EC",
"#F2FAFC",
"#FFFFFF",
"#3C8AA3",
"#E0F1F5"
],
"notes": "72-hour protection; no white marks on 100 colors",
"cond": "New",
"price": 2000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-TTA-SH-1L",
"brand": "Luseta",
"product": "Tea Tree & Argan Oil Shampoo",
"variant": "Tea Tree & Argan Oil",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 2,
"cat": "Hair",
"shape": "pumpL",
"c": [
"#5DA57F",
"#EAF4EE",
"#F6FBF8",
"#2B6B4A",
"#DDEEE4"
],
"notes": "Clarify and repair formula; color safe; for damaged and oily hair",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-RMC-SH-1L",
"brand": "Luseta",
"product": "Rosemary Mint Complex Strengthening Shampoo",
"variant": "Rosemary Mint Complex",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 2,
"cat": "Hair",
"shape": "pumpL",
"c": [
"#7FB89A",
"#20563C",
"#F4FBF7",
"#2F6F4F",
"#DFF0E6"
],
"notes": "Infused with rosemary, peppermint, biotin and argan oil; color safe; for all hair types",
"cond": "New",
"price": 5700,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "BBW-FFM-CC-236",
"brand": "Bath & Body Works",
"product": "Fine Fragrance Mist",
"variant": "Country Chic",
"size": "8 fl oz / 236 mL",
"ml": "236 mL",
"qty": 1,
"cat": "Fragrance",
"shape": "mist",
"c": [
"#E8C48E",
"#C9A06A",
"#FFF9EF",
"#9A6B2D",
"#F6EAD6"
],
"notes": "Dermatologist tested; for body and hair",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "BBW-FFM-OS-236",
"brand": "Bath & Body Works",
"product": "Fine Fragrance Mist",
"variant": "Open Sky",
"size": "8 fl oz / 236 mL",
"ml": "236 mL",
"qty": 3,
"cat": "Fragrance",
"shape": "mist",
"c": [
"#9EC3E6",
"#E6EFF8",
"#FFFFFF",
"#3A6E9E",
"#E1ECF7"
],
"notes": "Dermatologist tested; for body and hair",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "BBW-BW-FM-295",
"brand": "Bath & Body Works",
"product": "Body Wash",
"variant": "Fresh Musk",
"size": "10 fl oz / 295 mL",
"ml": "295 mL",
"qty": 1,
"cat": "Shower",
"shape": "flip",
"c": [
"#D9DDE4",
"#9AA3B2",
"#FFFFFF",
"#5A6477",
"#E9ECF1"
],
"notes": "Dermatologist tested; with pro-vitamin B5, aloe and vitamin E",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "BBW-FFM-WM-236",
"brand": "Bath & Body Works",
"product": "Fine Fragrance Mist",
"variant": "Warm Musk",
"size": "8 fl oz / 236 mL",
"ml": "236 mL",
"qty": 1,
"cat": "Fragrance",
"shape": "mist",
"c": [
"#C69A7A",
"#8C5E44",
"#FFF7F1",
"#7A4A30",
"#F1E1D5"
],
"notes": "Dermatologist tested; for body and hair",
"cond": "New",
"price": 4800,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DIF-RM-LCS-267",
"brand": "Difeel",
"product": "Leave-In Conditioning Spray",
"variant": "Rosemary & Mint with Biotin",
"size": "9 fl oz / 267 mL",
"ml": "267 mL",
"qty": 1,
"cat": "Hair",
"shape": "spray",
"c": [
"#6FAE86",
"#1F4D35",
"#F4FBF6",
"#2E7250",
"#DCEFE2"
],
"notes": "Helps prevent breakage, promote growth and repair split ends",
"cond": "New",
"price": 4800,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "HAI-CON-RICH-300",
"brand": "Fenty Hair",
"product": "Moisture Repair Conditioner",
"variant": "The Rich One",
"size": "10 fl oz / 300 mL",
"ml": "300 mL",
"qty": 3,
"cat": "Hair",
"shape": "tube",
"c": [
"#EADFD2",
"#4A3A33",
"#FFFFFF",
"#8C6B55",
"#EFE6DC"
],
"notes": "Moisture repair conditioner",
"cond": "New",
"price": 8000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-CM-BW-1L",
"brand": "Luseta",
"product": "Coconut Milk Body Wash",
"variant": "Coconut Milk",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#F4F0E6",
"#BFA98A",
"#FFFFFF",
"#8C7355",
"#EFE9DD"
],
"notes": "Nourishing and moisturizing formula; for all skin types",
"cond": "New",
"price": 3000,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-HA-BW-1L",
"brand": "Luseta",
"product": "Hyaluronic Acid Body Wash",
"variant": "Hyaluronic Acid",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#BCD9F0",
"#EAF3FB",
"#FFFFFF",
"#3E7CB0",
"#E2EEF8"
],
"notes": "Hydrating and smoothing formula; for all skin types",
"cond": "New",
"price": 7168,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-LC-BW-1L",
"brand": "Luseta",
"product": "Lavender & Collagen Body Wash",
"variant": "Lavender & Collagen",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 2,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#B9A2DA",
"#EFE8F8",
"#FFFFFF",
"#6A4E9C",
"#ECE4F6"
],
"notes": "Soothing and hydrating formula; for all skin types",
"cond": "New",
"price": 4796,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "LUS-CP-BW-1L",
"brand": "Luseta",
"product": "Collagen Peptides Body Wash",
"variant": "Collagen Peptides",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#F2C4B6",
"#FBEDE8",
"#FFFFFF",
"#B8664F",
"#F9E5DE"
],
"notes": "Rejuvenating and hydrating formula; for all skin types",
"cond": "New",
"price": 4796,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "SHM-GM-CV-800",
"brand": "Shower Mate",
"product": "Goat Milk Body Wash",
"variant": "Coconut & Vanilla",
"size": "27.05 fl oz / 800 mL",
"ml": "800 mL",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#F1E7D3",
"#6B4A2E",
"#FFFCF5",
"#8C6A3E",
"#F3EADB"
],
"notes": "Hydrating goat milk body wash",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "SHM-GM-MH-800",
"brand": "Shower Mate",
"product": "Goat Milk Body Wash",
"variant": "Manuka Honey",
"size": "27.05 fl oz / 800 mL",
"ml": "800 mL",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#E6B04A",
"#6B4A1E",
"#FFF8E6",
"#9C6A12",
"#F6E6C2"
],
"notes": "Nourishing goat milk body wash",
"cond": "New",
"price": 5500,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "CIR-VI-SG-1L",
"brand": "Ciroa",
"product": "Vanilla-icious Shower Gel",
"variant": "Vanilla, Brown Sugar & Amber",
"size": "33.8 fl oz / 1 L",
"ml": "1 L",
"qty": 1,
"cat": "Shower",
"shape": "pumpL",
"c": [
"#D9A36A",
"#F5E3CC",
"#FFF6EA",
"#8E5A2A",
"#F3E2CE"
],
"notes": "Australian-owned brand; shimmer shower gel",
"cond": "New",
"price": 5424,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "DOV-REF-CGT-BW-591",
"brand": "Dove",
"product": "Refresh Body Wash",
"variant": "Cucumber & Green Tea",
"size": "20 fl oz / 591 mL",
"ml": "591 mL",
"qty": 2,
"cat": "Shower",
"shape": "flip",
"c": [
"#BFE0A4",
"#EDF7E4",
"#FFFFFF",
"#4F8A2E",
"#E4F2DA"
],
"notes": "24-hour renewing moisture",
"cond": "New",
"price": 3840,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "MK-MAR-SAT-BLS-G",
"brand": "Michael Kors",
"product": "Marilyn Small Saffiano Satchel",
"variant": "Blush pink, gold-tone hardware",
"size": "Small",
"ml": "Small",
"qty": 1,
"cat": "Bags",
"shape": "bag",
"c": [
"#E3C4C5",
"#D8B3B4",
"#FFFFFF",
"#C9A55A",
"#F6E7E6"
],
"notes": "Saffiano leather; top zip; detachable strap",
"cond": "New",
"price": null,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "MK-GRW-XB-BLK-S",
"brand": "Michael Kors",
"product": "Greenwich Small Saffiano Crossbody",
"variant": "Black, silver-tone hardware",
"size": "Small",
"ml": "Small",
"qty": 1,
"cat": "Bags",
"shape": "bag",
"c": [
"#1B1B1E",
"#2A2A2E",
"#FFFFFF",
"#C3C8CF",
"#ECE9E4"
],
"notes": "Saffiano leather; flap with MK ring; adjustable strap",
"cond": "New",
"price": null,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "MK-MAR-SAT-BLK-S",
"brand": "Michael Kors",
"product": "Marilyn Medium Saffiano Satchel",
"variant": "Black, silver-tone hardware",
"size": "Medium",
"ml": "Medium",
"qty": 2,
"cat": "Bags",
"shape": "bag",
"c": [
"#1B1B1E",
"#2A2A2E",
"#FFFFFF",
"#C3C8CF",
"#ECE9E4"
],
"notes": "Saffiano leather; top zip; detachable strap",
"cond": "New",
"price": null,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "MK-MAR-SAT-BLK-G",
"brand": "Michael Kors",
"product": "Marilyn Medium Saffiano Satchel",
"variant": "Black, gold-tone hardware",
"size": "Medium",
"ml": "Medium",
"qty": 1,
"cat": "Bags",
"shape": "bag",
"c": [
"#1B1B1E",
"#2A2A2E",
"#FFFFFF",
"#C9A55A",
"#F1E9DD"
],
"notes": "Saffiano leather; top zip; detachable strap",
"cond": "New",
"price": null,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
},
{
"sku": "MK-MAR-TOT-BLK-S",
"brand": "Michael Kors",
"product": "Marilyn Medium Saffiano Tote",
"variant": "Black, silver-tone hardware",
"size": "Medium",
"ml": "Medium",
"qty": 2,
"cat": "Bags",
"shape": "bag",
"c": [
"#1B1B1E",
"#2A2A2E",
"#FFFFFF",
"#C3C8CF",
"#ECE9E4"
],
"notes": "Saffiano leather; top zip; side slip pockets; MK charm",
"cond": "New",
"price": null,
"status": "in_stock",
"eta": null,
"shippedOn": null,
"photo": null
}
];
